import fs from 'fs';

const translations = {
  en: { months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'], monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], daysNarrow: ['S', 'M', 'T', 'W', 'T', 'F', 'S'] },
  af: { months: ['Januarie', 'Februarie', 'Maart', 'April', 'Mei', 'Junie', 'Julie', 'Augustus', 'September', 'Oktober', 'November', 'Desember'], monthsShort: ['Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Des'], days: ['Sondag', 'Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrydag', 'Saterdag'], daysShort: ['Son', 'Maa', 'Din', 'Woe', 'Don', 'Vry', 'Sat'], daysNarrow: ['S', 'M', 'D', 'W', 'D', 'V', 'S'] },
  zu: { months: ['uJanuwari', 'uFebhuwari', 'uMashi', 'uApreli', 'uMeyi', 'uJuni', 'uJulayi', 'uAgasti', 'uSepthemba', 'uOktoba', 'uNovemba', 'uDisemba'], monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'Mey', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dis'], days: ['iSundu', 'uMsombuluko', 'uLwesibili', 'uLwesithathu', 'uLwesine', 'uLwesihlanu', 'iSaterdi'], daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], daysNarrow: ['S', 'M', 'T', 'W', 'T', 'F', 'S'] },
  xh: { months: ['Januwari', 'Februwari', 'Matshi', 'Apreli', 'Meyi', 'Juni', 'Julayi', 'Agasti', 'Septemba', 'Oktoba', 'Novemba', 'Disemba'], monthsShort: ['Jan', 'Feb', 'Mat', 'Apr', 'Mey', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dis'], days: ['Cawe', 'Mvulo', 'Lwesibini', 'Lwesithathu', 'Lwesine', 'Lwesihlanu', 'Mgqibelo'], daysShort: ['Caw', 'Mvu', 'Lwe', 'Lws', 'Lws', 'Lws', 'Mgq'], daysNarrow: ['C', 'M', 'L', 'L', 'L', 'L', 'M'] },
  sn: { months: ['Ndira', 'Kukadzi', 'Kurume', 'Kubvumbi', 'Chivabvu', 'Chikumi', 'Chikunguru', 'Nyamavhuvhu', 'Gunyana', 'Gumiguru', 'Gugurahundi', 'Mugabe'], monthsShort: ['Ndi', 'Kuk', 'Kur', 'Kub', 'Chi', 'Chi', 'Chi', 'Nya', 'Gun', 'Gum', 'Gug', 'Mug'], days: ['Svondo', 'Muvhuro', 'Chipiri', 'Chitatu', 'China', 'Chishanu', 'Mugovera'], daysShort: ['Svo', 'Muv', 'Chi', 'Chi', 'Chi', 'Chi', 'Mug'], daysNarrow: ['S', 'M', 'C', 'C', 'C', 'C', 'M'] },
  sw: { months: ['Januari', 'Februari', 'Machi', 'Aprili', 'Mei', 'Juni', 'Juli', 'Agosti', 'Septemba', 'Oktoba', 'Novemba', 'Desemba'], monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ago', 'Sep', 'Okt', 'Nov', 'Des'], days: ['Jumapili', 'Jumatatu', 'Jumanne', 'Jumatano', 'Alhamisi', 'Ijumaa', 'Jumamosi'], daysShort: ['Jum', 'Jum', 'Jum', 'Jum', 'Alh', 'Iju', 'Jum'], daysNarrow: ['J', 'J', 'J', 'J', 'A', 'I', 'J'] },
  ha: { months: ['Janairu', 'Febreru', 'Maris', 'Afirilu', 'Mayu', 'Juni', 'Yuli', 'Agusta', 'Satumba', 'Oktoba', 'Nuvemba', 'Disamba'], monthsShort: ['Jan', 'Feb', 'Mar', 'Afr', 'May', 'Jun', 'Yul', 'Agu', 'Sat', 'Okt', 'Nuv', 'Dis'], days: ['Lahadi', 'Lissafi', 'Talata', 'Larba', 'Alhamis', 'Juma', 'Asabar'], daysShort: ['Lah', 'Lis', 'Tal', 'Lar', 'Alh', 'Jum', 'Asa'], daysNarrow: ['L', 'L', 'T', 'L', 'A', 'J', 'A'] },
  ig: { months: ['Janu Mụ Ọnwa', 'Feb Mụ Ọnwa', 'Mach Mụ Ọnwa', 'Eprel Mụ Ọnwa', 'Mee Mụ Ọnwa', 'Juu Mụ Ọnwa', 'Jula Mụ Ọnwa', 'Agu Mụ Ọnwa', 'Sepu Mụ Ọnwa', 'Okto Mụ Ọnwa', 'Novu Mụ Ọnwa', 'Dis Mụ Ọnwa'], monthsShort: ['Janu', 'Feb', 'Mach', 'Epre', 'Mee', 'Juu', 'Jula', 'Agu', 'Sepu', 'Okto', 'Novu', 'Dis'], days: ['Ubọchị Sọpụ', 'Mọnde', 'Tiuzdee', 'Wenezde', 'Tọzde', 'Fraịde', 'Sọtọde'], daysShort: ['Ubọ', 'Mọn', 'Tiu', 'Wen', 'Tọz', 'Fra', 'Sọt'], daysNarrow: ['U', 'M', 'T', 'W', 'T', 'F', 'S'] },
  ar: { months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'], monthsShort: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'], days: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'], daysShort: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'], daysNarrow: ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'] },
  de: { months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'], monthsShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug'
