import { useState } from "react";
import {
  FileText,
  Plus,
  Search,
  Edit3,
  Trash2,
  Copy,
  MoreVertical,
  Eye,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DocumentEditor } from "@/components/documents/DocumentEditor";
import { TemplateForm, TemplateData } from "@/components/templates/TemplateForm";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

interface Template {
  id: string;
  name: string;
  description: string;
  lastModified: string;
  category: string;
  content: string;
  placeholders: string[];
  logoUrl?: string;
  logoPosition?: { x: number; y: number };
  fontFamily?: string;
}

const initialTemplates: Template[] = [
  {
    id: "1",
    name: "Client Action Plan",
    description: "Structured action plan with goals, timeline, and deliverables",
    lastModified: "2 days ago",
    category: "Plan",
    content: `CLIENT ACTION PLAN
================

Practice Number: [PracticeNumber]
Doctor Number: [DoctorNumber]

Client: [ClientName]
Date: [SessionDate]

EXECUTIVE SUMMARY
-----------------
[Summary]

KEY OBJECTIVES
--------------
1. [Content]

ACTION ITEMS
------------
• Priority 1: 
• Priority 2:
• Priority 3:

TIMELINE
--------
Week 1-2: Initial implementation
Week 3-4: Review and adjustment

NEXT STEPS
----------
[Details]

---
This document was generated by MedPad.`,
    placeholders: ["PracticeNumber", "DoctorNumber", "ClientName", "SessionDate", "Summary", "Content", "Details"],
  },
  {
    id: "2",
    name: "Session Summary",
    description: "Standard format for session notes and key takeaways",
    lastModified: "1 week ago",
    category: "Summary",
    content: `SESSION SUMMARY
===============

Practice Number: [PracticeNumber]
Doctor Number: [DoctorNumber]

Client: [ClientName]
Session Date: [SessionDate]
Duration: [Duration]

KEY DISCUSSION POINTS
---------------------
[Content]

OBSERVATIONS
------------
[Summary]

RECOMMENDATIONS
---------------
[Details]

FOLLOW-UP REQUIRED
------------------
• Next session scheduled for: 
• Action items assigned:

---
Confidential - MedPad`,
    placeholders: ["PracticeNumber", "DoctorNumber", "ClientName", "SessionDate", "Duration", "Content", "Summary", "Details"],
  },
  {
    id: "3",
    name: "Letter of Advice",
    description: "Professional advice letter with recommendations",
    lastModified: "2 weeks ago",
    category: "Letter",
    content: `LETTER OF ADVICE
================

Practice Number: [PracticeNumber]
Doctor Number: [DoctorNumber]

Date: [SessionDate]

Dear [ClientName],

RE: Professional Consultation

Following our recent consultation, I am writing to provide you with my professional advice and recommendations.

BACKGROUND
----------
[Summary]

ADVICE & RECOMMENDATIONS
------------------------
[Content]

IMPORTANT CONSIDERATIONS
------------------------
[Details]

Please do not hesitate to contact me if you have any questions regarding this advice.

Kind regards,

Dr. Smith
Professional Consultant`,
    placeholders: ["PracticeNumber", "DoctorNumber", "ClientName", "SessionDate", "Summary", "Content", "Details"],
  },
  {
    id: "4",
    name: "Invoice Template",
    description: "Billing template with service breakdown",
    lastModified: "1 month ago",
    category: "Invoice",
    content: `INVOICE
=======

Practice Number: [PracticeNumber]
Doctor Registration Number: [DoctorNumber]

Invoice Number: INV-[InvoiceNumber]
Date: [SessionDate]
Client: [ClientName]

SERVICES PROVIDED
-----------------
[Content]

PAYMENT DETAILS
---------------
Amount Due: $
Payment Terms: Due within 30 days

Thank you for your business.`,
    placeholders: ["PracticeNumber", "DoctorNumber", "InvoiceNumber", "SessionDate", "ClientName", "Content"],
  },
  {
    id: "5",
    name: "Medical Certificate",
    description: "Certificate for patients to substantiate absence from work",
    lastModified: "Just now",
    category: "Certificate",
    content: `MEDICAL CERTIFICATE
===================

Practice Number: [PracticeNumber]
Doctor Registration Number: [DoctorNumber]
Practice Address: [PracticeAddress]

I have today examined:

Patient: [PatientName]

Of: [PatientAddress]


Date of consultation: [ConsultationDate]

Time of Consultation: [ConsultationTime]


Nature of illness or injury: [NatureOfIllness]

..............................................................................................................

..............................................................................................................


Recommended sick leave from: [SickLeaveFrom] until [SickLeaveUntil] [Inclusive]

Other information / recommendations: [OtherRecommendations]

..............................................................................................................

..............................................................................................................

..............................................................................................................


Doctor's Name: [DoctorName]

Doctor's Signature: ................................................ Date: [SignatureDate]`,
    placeholders: ["PracticeNumber", "DoctorNumber", "PracticeAddress", "PatientName", "PatientAddress", "ConsultationDate", "ConsultationTime", "NatureOfIllness", "SickLeaveFrom", "SickLeaveUntil", "OtherRecommendations", "DoctorName", "SignatureDate"],
  },
];

const allDocuments = [
  { id: "1", name: "Action Plan - Sarah Johnson.pdf", date: "Dec 3, 2024", client: "Sarah Johnson", template: "Client Action Plan" },
  { id: "2", name: "Summary - Michael Chen.pdf", date: "Nov 30, 2024", client: "Michael Chen", template: "Session Summary" },
  { id: "3", name: "Advice Letter - Emma Williams.pdf", date: "Nov 28, 2024", client: "Emma Williams", template: "Letter of Advice" },
  { id: "4", name: "Invoice - John Davis.pdf", date: "Nov 25, 2024", client: "John Davis", template: "Invoice Template" },
  { id: "5", name: "Action Plan - Lisa Brown.pdf", date: "Nov 22, 2024", client: "Lisa Brown", template: "Client Action Plan" },
  { id: "6", name: "Summary - Robert Wilson.pdf", date: "Nov 20, 2024", client: "Robert Wilson", template: "Session Summary" },
  { id: "7", name: "Advice Letter - Anna Martinez.pdf", date: "Nov 18, 2024", client: "Anna Martinez", template: "Letter of Advice" },
  { id: "8", name: "Summary - David Lee.pdf", date: "Nov 15, 2024", client: "David Lee", template: "Session Summary" },
];

export default function Documents() {
  const { toast } = useToast();
  const [templates, setTemplates] = useState<Template[]>(initialTemplates);
  const [templateSearchQuery, setTemplateSearchQuery] = useState("");
  const [documentSearchQuery, setDocumentSearchQuery] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [isNewTemplateOpen, setIsNewTemplateOpen] = useState(false);
  const [editingTemplate, setEditingTemplate] = useState<Template | null>(null);
  const [templateToDelete, setTemplateToDelete] = useState<Template | null>(null);
  const [previewTemplate, setPreviewTemplate] = useState<Template | null>(null);

  const filteredTemplates = templates.filter((template) =>
    template.name.toLowerCase().includes(templateSearchQuery.toLowerCase()) ||
    template.category.toLowerCase().includes(templateSearchQuery.toLowerCase())
  );

  const filteredDocuments = allDocuments.filter((doc) =>
    doc.name.toLowerCase().includes(documentSearchQuery.toLowerCase()) ||
    doc.client.toLowerCase().includes(documentSearchQuery.toLowerCase()) ||
    doc.template.toLowerCase().includes(documentSearchQuery.toLowerCase())
  );

  const handleSelectTemplate = (template: Template) => {
    setSelectedTemplate(template);
  };

  const handleCloseEditor = () => {
    setSelectedTemplate(null);
  };

  const handleSaveDocument = (document: { name: string; content: string }) => {
    console.log("Saving document:", document);
    setSelectedTemplate(null);
    toast({
      title: "Document created",
      description: `"${document.name}" has been saved successfully`,
    });
  };

  const handleCreateTemplate = (template: TemplateData) => {
    const newTemplate: Template = {
      id: Date.now().toString(),
      name: template.name,
      description: template.description,
      category: template.category,
      content: template.content,
      lastModified: "Just now",
      placeholders: extractPlaceholders(template.content),
      logoUrl: template.logoUrl,
      logoPosition: template.logoPosition,
      fontFamily: template.fontFamily,
    };
    setTemplates([...templates, newTemplate]);
    toast({
      title: "Template Created",
      description: `"${template.name}" has been created successfully`,
    });
    setIsNewTemplateOpen(false);
  };

  const handleEditTemplate = (template: TemplateData) => {
    setTemplates(templates.map(t => 
      t.id === template.id 
        ? {
            ...t,
            name: template.name,
            description: template.description,
            category: template.category,
            content: template.content,
            lastModified: "Just now",
            placeholders: extractPlaceholders(template.content),
            logoUrl: template.logoUrl,
            logoPosition: template.logoPosition,
            fontFamily: template.fontFamily,
          }
        : t
    ));
    toast({
      title: "Template Updated",
      description: `"${template.name}" has been updated successfully`,
    });
    setEditingTemplate(null);
  };

  const handleDeleteTemplate = () => {
    if (!templateToDelete) return;
    setTemplates(templates.filter(t => t.id !== templateToDelete.id));
    toast({
      title: "Template Deleted",
      description: `"${templateToDelete.name}" has been deleted`,
    });
    setTemplateToDelete(null);
  };

  const extractPlaceholders = (content: string): string[] => {
    const matches = content.match(/\[([^\]]+)\]/g) || [];
    return [...new Set(matches.map(m => m.slice(1, -1)))];
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Templates</h1>
          <p className="mt-1 text-muted-foreground">
            Create and manage document templates
          </p>
        </div>
        <Dialog open={isNewTemplateOpen} onOpenChange={setIsNewTemplateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2">
              <Plus className="h-4 w-4" />
              New Template
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Create New Template</DialogTitle>
              <DialogDescription>
                Create a reusable document template with your practice letterhead
              </DialogDescription>
            </DialogHeader>
            <TemplateForm
              onSubmit={handleCreateTemplate}
              onCancel={() => setIsNewTemplateOpen(false)}
              mode="create"
            />
          </DialogContent>
        </Dialog>
      </div>

      {/* Template Search */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          placeholder="Search templates..."
          value={templateSearchQuery}
          onChange={(e) => setTemplateSearchQuery(e.target.value)}
          className="pl-10"
        />
      </div>

      {/* Templates Grid */}
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-4">Templates</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Select a template to start creating a document with voice drafting
        </p>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {filteredTemplates.map((template, index) => (
            <div
              key={template.id}
              className="group rounded-xl border border-border bg-card p-5 shadow-sm transition-all duration-300 hover:shadow-md hover:border-primary/30 text-left cursor-pointer"
              style={{ animationDelay: `${index * 50}ms` }}
            >
              <div className="flex items-start justify-between mb-3">
                <div 
                  className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent transition-colors group-hover:bg-primary/10"
                  onClick={() => handleSelectTemplate(template)}
                >
                  <FileText className="h-5 w-5 text-accent-foreground group-hover:text-primary" />
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <MoreVertical className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => setPreviewTemplate(template)}>
                      <Eye className="h-4 w-4 mr-2" />
                      Preview Template
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => setEditingTemplate(template)}>
                      <Edit3 className="h-4 w-4 mr-2" />
                      Edit Template
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleSelectTemplate(template)}>
                      <Copy className="h-4 w-4 mr-2" />
                      Use Template
                    </DropdownMenuItem>
                    <DropdownMenuItem 
                      onClick={() => setTemplateToDelete(template)}
                      className="text-destructive focus:text-destructive"
                    >
                      <Trash2 className="h-4 w-4 mr-2" />
                      Delete Template
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              <div onClick={() => handleSelectTemplate(template)}>
                <h3 className="font-medium text-foreground mb-1">{template.name}</h3>
                <p className="text-sm text-muted-foreground mb-3 line-clamp-2">
                  {template.description}
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground">
                    {template.lastModified}
                  </span>
                  <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                    {template.category}
                  </span>
                </div>
              </div>
            </div>
          ))}

          {/* Add New Template Card */}
          <div 
            onClick={() => setIsNewTemplateOpen(true)}
            className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card/50 p-5 text-center transition-colors hover:bg-muted/30 cursor-pointer"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted mb-3">
              <Plus className="h-5 w-5 text-muted-foreground" />
            </div>
            <p className="font-medium text-muted-foreground">Create Template</p>
          </div>
        </div>
      </div>

      {/* All Documents */}
      <div>
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between mb-4">
          <h2 className="text-lg font-semibold text-foreground">All Documents</h2>
          <div className="relative max-w-xs">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              placeholder="Search documents..."
              value={documentSearchQuery}
              onChange={(e) => setDocumentSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
        </div>
        <div className="rounded-xl border border-border bg-card shadow-sm overflow-hidden">
          <div className="divide-y divide-border max-h-[400px] overflow-y-auto">
            {filteredDocuments.length > 0 ? (
              filteredDocuments.map((doc) => (
                <div
                  key={doc.id}
                  className="flex items-center gap-4 p-4 hover:bg-muted/30 transition-colors"
                >
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent">
                    <FileText className="h-5 w-5 text-accent-foreground" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-foreground truncate">{doc.name}</p>
                    <p className="text-sm text-muted-foreground">
                      {doc.client} · {doc.date} · <span className="text-primary/70">{doc.template}</span>
                    </p>
                  </div>
                  <div className="flex gap-1">
                    <Button variant="ghost" size="icon" className="h-8 w-8">
                      <Edit3 className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8">
                      <Copy className="h-4 w-4" />
                    </Button>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive">
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              ))
            ) : (
              <div className="p-8 text-center text-muted-foreground">
                No documents found matching your search.
              </div>
            )}
          </div>
        </div>
        <p className="text-sm text-muted-foreground mt-2">
          Showing {filteredDocuments.length} of {allDocuments.length} documents
        </p>
      </div>

      {/* Document Editor Modal */}
      {selectedTemplate && (
        <DocumentEditor
          template={selectedTemplate}
          onClose={handleCloseEditor}
          onSave={handleSaveDocument}
        />
      )}

      {/* Edit Template Dialog */}
      <Dialog open={!!editingTemplate} onOpenChange={(open) => !open && setEditingTemplate(null)}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Template</DialogTitle>
            <DialogDescription>
              Modify this template's content, logo, and settings
            </DialogDescription>
          </DialogHeader>
          {editingTemplate && (
            <TemplateForm
              initialData={{
                id: editingTemplate.id,
                name: editingTemplate.name,
                description: editingTemplate.description,
                category: editingTemplate.category,
                content: editingTemplate.content,
                logoUrl: editingTemplate.logoUrl,
                logoPosition: editingTemplate.logoPosition,
                fontFamily: editingTemplate.fontFamily,
              }}
              onSubmit={handleEditTemplate}
              onCancel={() => setEditingTemplate(null)}
              mode="edit"
            />
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!templateToDelete} onOpenChange={(open) => !open && setTemplateToDelete(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Template</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete "{templateToDelete?.name}"? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDeleteTemplate} className="bg-destructive hover:bg-destructive/90">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Template Preview Dialog */}
      <Dialog open={!!previewTemplate} onOpenChange={(open) => !open && setPreviewTemplate(null)}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Template Preview: {previewTemplate?.name}</DialogTitle>
            <DialogDescription>
              Preview of the template content and formatting
            </DialogDescription>
          </DialogHeader>
          {previewTemplate && (
            <div className="space-y-4">
              {/* Template Meta */}
              <div className="flex items-center gap-4 text-sm text-muted-foreground">
                <span className="rounded-full bg-muted px-2.5 py-0.5 font-medium">
                  {previewTemplate.category || "Uncategorized"}
                </span>
                <span>Last modified: {previewTemplate.lastModified}</span>
                {previewTemplate.fontFamily && (
                  <span>Font: {previewTemplate.fontFamily}</span>
                )}
              </div>

              {/* Template Preview */}
              <div className="border border-border rounded-lg p-6 bg-card/50">
                {/* Logo Preview */}
                {previewTemplate.logoUrl && (
                  <div 
                    className="mb-4"
                    style={{ 
                      textAlign: previewTemplate.logoPosition?.x && previewTemplate.logoPosition.x > 66 
                        ? 'right' 
                        : previewTemplate.logoPosition?.x && previewTemplate.logoPosition.x > 33 
                          ? 'center' 
                          : 'left' 
                    }}
                  >
                    <img 
                      src={previewTemplate.logoUrl} 
                      alt="Template logo" 
                      className="max-h-16 inline-block"
                    />
                  </div>
                )}
                
                {/* Content Preview */}
                <pre 
                  className={`whitespace-pre-wrap text-sm text-foreground font-${previewTemplate.fontFamily || 'sans'}`}
                  style={{ fontFamily: previewTemplate.fontFamily === 'sans' ? 'inherit' : undefined }}
                >
                  {previewTemplate.content}
                </pre>
              </div>

              {/* Placeholders */}
              {previewTemplate.placeholders && previewTemplate.placeholders.length > 0 && (
                <div>
                  <p className="text-sm font-medium text-foreground mb-2">Dynamic Placeholders:</p>
                  <div className="flex flex-wrap gap-2">
                    {previewTemplate.placeholders.map((placeholder) => (
                      <span 
                        key={placeholder} 
                        className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full"
                      >
                        [{placeholder}]
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex gap-3 pt-4 border-t border-border">
                <Button variant="outline" onClick={() => setPreviewTemplate(null)} className="flex-1">
                  Close
                </Button>
                <Button 
                  onClick={() => {
                    handleSelectTemplate(previewTemplate);
                    setPreviewTemplate(null);
                  }} 
                  className="flex-1"
                >
                  Use Template
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
