import { useState } from "react";
import {
  FileText,
  Plus,
  Search,
  Edit3,
  Trash2,
  Copy,
  MoreVertical,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { DocumentEditor } from "@/components/documents/DocumentEditor";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface Template {
  id: string;
  name: string;
  description: string;
  lastModified: string;
  category: string;
  content: string;
  placeholders: string[];
}

const mockTemplates: Template[] = [
  {
    id: "1",
    name: "Client Action Plan",
    description: "Structured action plan with goals, timeline, and deliverables",
    lastModified: "2 days ago",
    category: "Plan",
    content: `CLIENT ACTION PLAN
================

Client: [ClientName]
Date: [SessionDate]
Prepared by: Dr. Smith

EXECUTIVE SUMMARY
-----------------
[Summary]

KEY OBJECTIVES
--------------
1. [Content]

ACTION ITEMS
------------
• Priority 1: 
• Priority 2:
• Priority 3:

TIMELINE
--------
Week 1-2: Initial implementation
Week 3-4: Review and adjustment

NEXT STEPS
----------
[Details]

---
This document was generated by MedPad.`,
    placeholders: ["ClientName", "SessionDate", "Summary", "Content", "Details"],
  },
  {
    id: "2",
    name: "Session Summary",
    description: "Standard format for session notes and key takeaways",
    lastModified: "1 week ago",
    category: "Summary",
    content: `SESSION SUMMARY
===============

Client: [ClientName]
Session Date: [SessionDate]
Duration: [Duration]

KEY DISCUSSION POINTS
---------------------
[Content]

OBSERVATIONS
------------
[Summary]

RECOMMENDATIONS
---------------
[Details]

FOLLOW-UP REQUIRED
------------------
• Next session scheduled for: 
• Action items assigned:

---
Confidential - MedPad`,
    placeholders: ["ClientName", "SessionDate", "Duration", "Content", "Summary", "Details"],
  },
  {
    id: "3",
    name: "Letter of Advice",
    description: "Professional advice letter with recommendations",
    lastModified: "2 weeks ago",
    category: "Letter",
    content: `LETTER OF ADVICE
================

Date: [SessionDate]

Dear [ClientName],

RE: Professional Consultation

Following our recent consultation, I am writing to provide you with my professional advice and recommendations.

BACKGROUND
----------
[Summary]

ADVICE & RECOMMENDATIONS
------------------------
[Content]

IMPORTANT CONSIDERATIONS
------------------------
[Details]

Please do not hesitate to contact me if you have any questions regarding this advice.

Kind regards,

Dr. Smith
Professional Consultant`,
    placeholders: ["ClientName", "SessionDate", "Summary", "Content", "Details"],
  },
  {
    id: "4",
    name: "Invoice Template",
    description: "Billing template with service breakdown",
    lastModified: "1 month ago",
    category: "Invoice",
    content: `INVOICE
=======

Invoice Number: INV-[InvoiceNumber]
Date: [SessionDate]
Client: [ClientName]

SERVICES PROVIDED
-----------------
[Content]

PAYMENT DETAILS
---------------
Amount Due: $
Payment Terms: Due within 30 days

Thank you for your business.`,
    placeholders: ["InvoiceNumber", "SessionDate", "ClientName", "Content"],
  },
];

const recentDocuments = [
  { id: "1", name: "Action Plan - Sarah Johnson.pdf", date: "Dec 3, 2024", client: "Sarah Johnson" },
  { id: "2", name: "Summary - Michael Chen.pdf", date: "Nov 30, 2024", client: "Michael Chen" },
  { id: "3", name: "Advice Letter - Emma Williams.pdf", date: "Nov 28, 2024", client: "Emma Williams" },
];

export default function Documents() {
  const { toast } = useToast();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [isNewTemplateOpen, setIsNewTemplateOpen] = useState(false);
  const [newTemplate, setNewTemplate] = useState({
    name: "",
    description: "",
    category: "",
    content: "",
  });

  const filteredTemplates = mockTemplates.filter((template) =>
    template.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleSelectTemplate = (template: Template) => {
    setSelectedTemplate(template);
  };

  const handleCloseEditor = () => {
    setSelectedTemplate(null);
  };

  const handleSaveDocument = (document: { name: string; content: string }) => {
    console.log("Saving document:", document);
    setSelectedTemplate(null);
    toast({
      title: "Document created",
      description: `"${document.name}" has been saved successfully`,
    });
  };

  const handleCreateTemplate = () => {
    if (!newTemplate.name.trim() || !newTemplate.content.trim()) {
      toast({
        title: "Error",
        description: "Template name and content are required",
        variant: "destructive",
      });
      return;
    }

    toast({
      title: "Template Created",
      description: `"${newTemplate.name}" has been created successfully`,
    });
    setIsNewTemplateOpen(false);
    setNewTemplate({ name: "", description: "", category: "", content: "" });
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Documents</h1>
          <p className="mt-1 text-muted-foreground">
            Create and manage document templates
          </p>
        </div>
        <Dialog open={isNewTemplateOpen} onOpenChange={setIsNewTemplateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2">
              <Plus className="h-4 w-4" />
              New Template
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>Create New Template</DialogTitle>
              <DialogDescription>Create a reusable document template</DialogDescription>
            </DialogHeader>
            <div className="space-y-4 pt-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-foreground">Template Name *</label>
                  <Input
                    placeholder="e.g., Progress Report"
                    value={newTemplate.name}
                    onChange={(e) => setNewTemplate({ ...newTemplate, name: e.target.value })}
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-foreground">Category</label>
                  <Input
                    placeholder="e.g., Report, Letter, Plan"
                    value={newTemplate.category}
                    onChange={(e) => setNewTemplate({ ...newTemplate, category: e.target.value })}
                  />
                </div>
              </div>
              <div>
                <label className="text-sm font-medium text-foreground">Description</label>
                <Input
                  placeholder="Brief description of the template"
                  value={newTemplate.description}
                  onChange={(e) => setNewTemplate({ ...newTemplate, description: e.target.value })}
                />
              </div>
              <div>
                <label className="text-sm font-medium text-foreground">Content *</label>
                <p className="text-xs text-muted-foreground mb-2">
                  Use [PlaceholderName] for dynamic fields like [ClientName], [SessionDate]
                </p>
                <Textarea
                  placeholder="Enter template content with placeholders..."
                  value={newTemplate.content}
                  onChange={(e) => setNewTemplate({ ...newTemplate, content: e.target.value })}
                  rows={10}
                  className="font-mono text-sm"
                />
              </div>
              <Button onClick={handleCreateTemplate} className="w-full">
                Create Template
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Search */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          placeholder="Search templates..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="pl-10"
        />
      </div>

      {/* Templates Grid */}
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-4">Templates</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Select a template to start creating a document with voice drafting
        </p>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {filteredTemplates.map((template, index) => (
            <div
              key={template.id}
              onClick={() => handleSelectTemplate(template)}
              className="group rounded-xl border border-border bg-card p-5 shadow-sm transition-all duration-300 hover:shadow-md hover:border-primary/30 text-left cursor-pointer"
              style={{ animationDelay: `${index * 50}ms` }}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent transition-colors group-hover:bg-primary/10">
                  <FileText className="h-5 w-5 text-accent-foreground group-hover:text-primary" />
                </div>
                <Button 
                  variant="ghost" 
                  size="icon" 
                  className="h-8 w-8 opacity-0 group-hover:opacity-100 transition-opacity"
                  onClick={(e) => e.stopPropagation()}
                >
                  <MoreVertical className="h-4 w-4" />
                </Button>
              </div>
              <h3 className="font-medium text-foreground mb-1">{template.name}</h3>
              <p className="text-sm text-muted-foreground mb-3 line-clamp-2">
                {template.description}
              </p>
              <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground">
                  {template.lastModified}
                </span>
                <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground">
                  {template.category}
                </span>
              </div>
            </div>
          ))}

          {/* Add New Template Card */}
          <div 
            onClick={() => setIsNewTemplateOpen(true)}
            className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card/50 p-5 text-center transition-colors hover:bg-muted/30 cursor-pointer"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted mb-3">
              <Plus className="h-5 w-5 text-muted-foreground" />
            </div>
            <p className="font-medium text-muted-foreground">Create Template</p>
          </div>
        </div>
      </div>

      {/* Recent Documents */}
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-4">Recent Documents</h2>
        <div className="rounded-xl border border-border bg-card shadow-sm overflow-hidden">
          <div className="divide-y divide-border">
            {recentDocuments.map((doc) => (
              <div
                key={doc.id}
                className="flex items-center gap-4 p-4 hover:bg-muted/30 transition-colors"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent">
                  <FileText className="h-5 w-5 text-accent-foreground" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-foreground truncate">{doc.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {doc.client} · {doc.date}
                  </p>
                </div>
                <div className="flex gap-1">
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <Edit3 className="h-4 w-4" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <Copy className="h-4 w-4" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive">
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Document Editor Modal */}
      {selectedTemplate && (
        <DocumentEditor
          template={selectedTemplate}
          onClose={handleCloseEditor}
          onSave={handleSaveDocument}
        />
      )}
    </div>
  );
}